apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Values.name }}"
data:
  {{ range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{ end }}
